name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
<<<<<<< HEAD
        node-version: [14]
=======
        node-version: '14'
>>>>>>> bc13246abb5962d31f1e6ae2212b80d492cdc5ca
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
